version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@_123456789000Sa
      - POSTGRES_DB=crowdfund
    ports:
      - '5433:5432'

  crowdfunding:
    container_name: crowdfunding_api
    image: atwa4/crowdfunding-api:latest
    restart: always
    ports:
      - '8082:8082'
    environment:
      - PROFILE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/products
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=@_123456789000Sa
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - WORK_DIR=home/kayany_website/itways
      - DOMAIN=http://35.197.20.122:8082
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=salahsayedatwa@gmail.com
      - SMTP_PASSWORD=ovviocmfvepvoesq
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - psql-db
    volumes:
      - /home/kayany_website/itways:/home/kayany_website/itways
    networks:
      - webnet
            
  crowdfunding-panel:
    container_name: crowdfunding_admin
    image: atwa4/crowdfunding-panel:latest
    restart: always
    ports:
      - '8085:8085'
    environment:
      - PROFILE=test
    depends_on:
      - crowdfunding
    networks:
      - webnet

 

  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    environment:
      - PROFILE=test
    networks:
      - webnet
    depends_on:
      - crowdfunding
      - crowdfunding-panel

networks:
  webnet:
