version: "3.8"

services:
      
  itwaysai:
    container_name: itways-ai-api
    image: atwa4/itways-ai-api:latest
    restart: always
    ports:
      - '8082:8082'
    environment:
      - PROFILE=prod
      - AI_ENDPOINT=http://host.docker.internal:11434
      - AI_URL=host.docker.internal
      - AI_MODEL=codellama:7b
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/kayany_website/itways:/home/kayany_website/itways
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    environment:
      - PROFILE=test
    depends_on:
      - itwaysai
    networks:
      - webnet

networks:
  webnet:
