version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@_123456789000Sa
      - POSTGRES_DB=crowdfund
    ports:
      - '5433:5432'

  crowdfunding:
    container_name: crowdfunding_api
    image: atwa4/crowdfunding-api:latest
    restart: always
    ports:
      - '8082:8082'
    environment:
      - PROFILE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/crowdfund
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=@_123456789000Sa
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - WORK_DIR=/home/salahsayedatwa/apps/backend/
      - DOMAIN=http://4.227.163.50:8082
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - psql-db

  gatway:
    container_name: gatway_api
    image: atwa4/gatway-api:latest
    restart: always
    ports:
      - '8083:8083'
    environment:
      - PROFILE=prod
    depends_on:
      - crowdfunding
            
  crowdfunding-panel:
    container_name: crowdfunding_admin
    image: atwa4/crowdfunding-panel:latest
    restart: always
    ports:
      - '8085:8085'
    environment:
      - PROFILE=test
    depends_on:
      - crowdfunding
